Reduce purge period from 30 to 14 days.
unioslo/tsdfx pull request #129
Opened 2018-02-13 10:59 UTC by petterreinholdtsen

If a file has been successfully transfered for 14 days, there is no
need to keep the original copy in the source directory.

2018-02-13 14:03 UTC, petterreinholdtsen commented
The build failures with clang and gcc are fixed in pull request #130 and #131.

2018-02-14 11:22 UTC, dag-erling commented
1. Please submit working code only.
2. This should be parametrized, preferably in a configuration file, but a command-line switch works too.

2018-02-14 11:28 UTC, petterreinholdtsen commented
[Dag-Erling Smørgrav]
> 1. Please submit working code only.

What do you mean?

-- 
Happy hacking
Petter Reinholdtsen

2018-02-23 09:09 UTC, petterreinholdtsen commented
Note, there is already a command line switch, -d.

2018-02-23 09:57 UTC, dag-erling commented on bin/tsdfx/tsdfx.8
> +copied to the destination and their mtime is more than sec in the
`sec` here and on the next line should be `.Ar sec` on a line of its own.

2018-02-23 09:57 UTC, dag-erling requested changes
Markup errors in the man page.

2018-02-23 10:00 UTC, dag-erling commented on bin/tsdfx/tsdfx.8
> +copied to the destination and their mtime is more than sec in the
Sorry, `.Va`, not `.Ar`.

2018-02-23 10:03 UTC, petterreinholdtsen commented
Sure, why not. :)

2018-02-23 10:10 UTC, dag-erling approved these changes

2018-02-23 10:10 UTC, merged