Fix problems blocking jenkins from checking the code.
unioslo/tsdfx pull request #132
Opened 2018-02-14 12:50 UTC by petterreinholdtsen

This pull request merge the changes from pull request #130 and #131 into one pull requests.

2018-02-15 14:44 UTC, dag-erling requested changes

2018-02-15 14:44 UTC, dag-erling commented on lib/libtsd/tsd_task.c
> +		else if (getuid() != geteuid() && setuid(getuid()) != 0) {
Pull up as per [style(9)](https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9), or just get rid of the braces altogether, as they are unnecessary once you remove the incorrect `goto fail`.

2018-02-15 14:44 UTC, dag-erling commented on lib/libtsd/tsd_task.c
> +			goto fail;
You are now in the child process. The `fail` target is in the parent code. Using `goto fail` here will result in the child process “becoming” a new, duplicate tsdfx master process which will compete with its parent (and possibly occupy a task slot in the parent forever). Assuming that `setgid()` or `setuid()` will either never fail or always fail, this change turns tsdfx into a fork bomb that also heavily exercises the file system.

The correct behavior is to just fall through to the `_exit(1)` at the bottom of the child block.

2018-02-15 14:44 UTC, dag-erling commented on lib/libtsd/tsd_task.c
>  		(*t->func)(t->ud);
This should be in an `else` block as well.

2018-02-22 12:23 UTC, petterreinholdtsen commented
I've updated the setuid() part of the patch.

2018-02-23 09:30 UTC, merged